title: "Giacomo Ceccarini | Game Developer Portfolio"
description: "Game developer portfolio"
baseurl: ""
url: "https://giacomoCeccarini.github.io"

# Personal info — edit these
author:
  name: "Giacomo Ceccarini"
  title: "Junior Gameplay Programmer"
  bio: "Currently Master’s Student in Computer Engineering at Sapienza University in Rome. Been playing games since 4, been trying to make games since 9. I enjoy turning ideas into interactive experiences for everyone, and by doing so, i continuously improve my skills through practical small projects"
  photo: "/assets/img/profile.jpg"
  resume: "/assets/resume.pdf"

social:
  linkedin: "https://www.linkedin.com/in/giacomo-ceccarini-88a3103b6/"
  github: "https://github.com/ItalianJackWEIRD"

about:
  title: "Hi, I'm Giacomo Ceccarini"
  body: |
    I'm a Computer Engineering graduate from Roma Tre University, currently completing my Master's in Engineering in Computer Science at Sapienza.

    I'm 24 and I've been playing games since I was a kid — that <strong>passion</strong> never left, it just became <strong>more technical</strong>. I focus on gameplay and systems programming, with a particular interest in how games <strong>feel to play</strong>, not just how they work. But I've never wanted to stop at code alone. I believe games are the <strong>ultimate form of art</strong>: the only medium that simultaneously engages audio, vision and touch. And if you believe that, you have to care about all of it.
    So that's what I do. I write code, find my way around Blender, and compose and implement audio — because understanding how all the pieces connect makes me a better programmer, and a <strong>better collaborator</strong>.

collections:
  projects:
    output: true
    permalink: /projects/:name/

markdown: kramdown

webrick:
  mime_types:
    video/mp4: [mp4]
